const QUICKCOPY_KEY = 'quickcopy_wallets';
const SETTINGS_KEY = 'quickcopy_settings';
const INJECTED = 'data-quickcopy-injected';
const DEFAULT_SETTINGS = { color: 'lime', label: true, shape: 'rounded', size: 'medium' };
const REQUEST_WORDS = /\b(wallet|address|addr|whitelist|allowlist|mint|drop|wl|send|share|paste|submit|claim)\b/i;
const REQUEST_PHRASES = /\b(drop|send|share|paste|submit|reply|comment|claim)\b.{0,60}\b(your|my|wallet|address|addr|below|here|whitelist|wl)\b|\b(your|my|wallet|address|addr|below|here|whitelist|wl)\b.{0,60}\b(drop|send|share|paste|submit|reply|comment|claim)\b/i;
const NON_LATIN_REQUEST = /[\u0600-\u06FF\u0750-\u077F]/;
const NETWORK_WORDS = { Ethereum: /\b(evm|ethereum|eth|base|polygon|arbitrum|optimism|bnb|avalanche)\b/i, Solana: /\bsolana|sol\b/i };
const SCRIPT_REQUEST = /\u0648\u0627\u0644\u062a|\u0622\u062f\u0631\u0633|\u0627\u062f\u0631\u0633|\u0628\u0641\u0631\u0633|\u0628\u0632\u0627\u0631|\u0627\u0631\u0633\u0627\u0644/i;
const fallbackWallets = [{ id: 'demo', name: 'Main Ethereum', network: 'Ethereum', address: '0x7A3f19d5B7D6a44f6aE3cE6aC7bF1b2a91cB' }];

function reportQuickCopyError(stage, error) { console.warn(`[QuickCopy] ${stage}`, error); }
function readStorage(key, fallback) { return new Promise((resolve) => chrome.storage.local.get({ [key]: fallback }, (result) => resolve(result[key]))); }
function short(value) { return value.length > 18 ? `${value.slice(0, 8)}...${value.slice(-6)}` : value; }
function groupFor(wallet) { return NETWORK_WORDS.Solana.test(`${wallet.name} ${wallet.network}`) ? 'Solana' : 'Ethereum'; }
function isWalletRequest(text) { const normalized = text.replace(/\s+/g, ' ').trim(); if (!normalized || normalized.length > 1000) return false; if (REQUEST_PHRASES.test(normalized)) return true; if (REQUEST_WORDS.test(normalized) && (NETWORK_WORDS.Ethereum.test(normalized) || NETWORK_WORDS.Solana.test(normalized))) return true; return NON_LATIN_REQUEST.test(normalized) && SCRIPT_REQUEST.test(normalized) && normalized.length > 12; }
function postText(post) { return post.innerText || post.textContent || ''; }
function findActions(post) { return post.querySelector('[role="group"]') || post.querySelector('[data-testid="reply"]')?.parentElement?.parentElement || null; }
function isDarkSurface() { const colors = [getComputedStyle(document.body).backgroundColor, getComputedStyle(document.documentElement).backgroundColor]; const color = colors.find((value) => value && !value.includes('0)')) || 'rgb(255,255,255)'; const rgb = color.match(/\d+(?:\.\d+)?/g)?.map(Number) || [255, 255, 255]; return (rgb[0] * 0.299 + rgb[1] * 0.587 + rgb[2] * 0.114) < 145; }
function clearInjected(post) { post.removeAttribute(INJECTED); post.querySelectorAll('.quickcopy-wrapper').forEach((node) => node.remove()); }
function networkMark(network) { return network === 'Solana' ? '<svg class="quickcopy-network-mark" viewBox="0 0 24 24" aria-label="Solana"><path d="M5 6h11l3 3H8L5 6Zm3 4h11l-3 3H5l3-3Zm-3 5h11l3 3H8l-3-3Z" fill="currentColor"/></svg>' : '<svg class="quickcopy-network-mark" viewBox="0 0 24 24" aria-label="Ethereum"><path d="m12 2 6 10-6 3.5L6 12l6-10Zm0 15.5 6-3.3-6 7.8-6-7.8 6 3.3Z" fill="currentColor"/></svg>'; }
function isVisible(element) { const rect = element?.getBoundingClientRect?.(); return Boolean(rect && rect.width && rect.height); }
function findComposer(scope) { const selectors = ['[contenteditable="true"][role="textbox"]', '[data-testid^="tweetTextarea"] [contenteditable="true"]', 'textarea[data-testid^="tweetTextarea"]']; const candidates = selectors.flatMap((selector) => [...scope.querySelectorAll(selector)]); return candidates.find(isVisible) || null; }
function waitForComposer(post) { return new Promise((resolve) => { const started = Date.now(); const tick = () => { const composer = findComposer(post) || findComposer(document); if (composer) return resolve(composer); if (Date.now() - started > 1800) return resolve(null); window.setTimeout(tick, 60); }; tick(); }); }
function insertIntoComposer(composer, value) { composer.focus(); if (composer instanceof HTMLTextAreaElement || composer instanceof HTMLInputElement) { const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value')?.set; setter?.call(composer, (composer.value || '') + value); composer.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: value })); return; } const selection = window.getSelection(); const range = document.createRange(); range.selectNodeContents(composer); range.collapse(false); selection?.removeAllRanges(); selection?.addRange(range); const inserted = document.execCommand('insertText', false, value); if (!inserted) { const text = document.createTextNode(value); range.insertNode(text); range.setStartAfter(text); range.collapse(true); selection?.removeAllRanges(); selection?.addRange(range); } composer.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: value })); composer.dispatchEvent(new Event('change', { bubbles: true })); }
async function pasteIntoReply(post, value) { let composer = findComposer(post) || findComposer(document); if (!composer) { post.querySelector('[data-testid="reply"], button[aria-label*="Reply" i]')?.click(); composer = await waitForComposer(post); } if (!composer) return false; insertIntoComposer(composer, value); return true; }

async function addQuickCopy(post) {
  if (post.hasAttribute(INJECTED) || !isWalletRequest(postText(post))) return;
  const actions = findActions(post); if (!actions) return;
  post.setAttribute(INJECTED, 'true');
  const wallets = (await readStorage(QUICKCOPY_KEY, fallbackWallets)).slice(0, 10); if (!wallets.length) { post.removeAttribute(INJECTED); return; }
  const settings = { ...DEFAULT_SETTINGS, ...(await readStorage(SETTINGS_KEY, DEFAULT_SETTINGS)) }; const shape = settings.shape === 'circle' ? 'circle' : 'rounded';
  actions.classList.add('quickcopy-anchor-host');
  const wrapper = document.createElement('div'); wrapper.className = 'quickcopy-wrapper quickcopy-fixed';
  const trigger = document.createElement('button'); trigger.className = `quickcopy-trigger quickcopy-color-${settings.color} quickcopy-shape-${shape} quickcopy-size-${settings.size} ${isDarkSurface() ? 'quickcopy-on-dark' : 'quickcopy-on-light'}`; trigger.setAttribute('aria-label', 'Choose wallet address'); const triggerLogo = '<svg class="quickcopy-brand-mark" viewBox="0 0 128 128" aria-hidden="true"><rect width="128" height="128" rx="28" fill="currentColor"/><rect x="36" y="36" width="40" height="40" rx="6" fill="none" stroke="#000" stroke-width="7"/><rect x="52" y="52" width="40" height="40" rx="6" fill="#000"/><path d="M78 58 L68 78 L76 78 L70 92 L88 68 L80 68 L86 58 Z" fill="currentColor"/></svg>'; trigger.innerHTML = settings.label ? `${triggerLogo}<span class="quickcopy-text">COPY WALLET</span><span class="quickcopy-chevron">⌄</span>` : triggerLogo;
  const menu = document.createElement('div'); menu.className = 'quickcopy-menu'; menu.setAttribute('role', 'menu');
  const heading = document.createElement('div'); heading.className = 'quickcopy-menu-heading'; heading.innerHTML = '<span>YOUR ADDRESSES</span><small>ONE CLICK COPY</small>'; menu.appendChild(heading);
  const list = document.createElement('div'); list.className = 'quickcopy-list'; menu.appendChild(list);
  const copyWallet = async (wallet, item) => { try { if (!navigator.clipboard?.writeText) throw new Error('Clipboard API is unavailable.'); await navigator.clipboard.writeText(wallet.address); const pasted = await pasteIntoReply(post, wallet.address); item.classList.add('is-copied'); item.querySelector('.quickcopy-copy').textContent = pasted ? 'PASTED' : 'COPIED'; trigger.classList.add('is-copied'); const label = trigger.querySelector('.quickcopy-text'); if (label) label.textContent = pasted ? 'PASTED' : 'COPIED'; menu.classList.remove('is-open'); setTimeout(() => { item.classList.remove('is-copied'); item.querySelector('.quickcopy-copy').textContent = 'COPY'; trigger.classList.remove('is-copied'); if (label) label.textContent = 'COPY WALLET'; }, 1400); } catch (error) { reportQuickCopyError('copy or reply insertion failed', error); item.querySelector('.quickcopy-copy').textContent = 'TRY AGAIN'; } };
  wallets.forEach((wallet) => { const item = document.createElement('button'); item.className = 'quickcopy-item'; item.setAttribute('role', 'menuitem'); item.innerHTML = `<span class="quickcopy-network-icon network-${groupFor(wallet).toLowerCase()}">${networkMark(groupFor(wallet))}</span><span class="quickcopy-item-info"><b></b><small></small></span><span class="quickcopy-copy">COPY</span>`; item.querySelector('b').textContent = wallet.name; item.querySelector('small').textContent = `${groupFor(wallet)} · ${short(wallet.address)}`; item.onclick = (event) => { event.stopPropagation(); copyWallet(wallet, item); }; list.appendChild(item); });
  trigger.onclick = (event) => { event.stopPropagation(); document.querySelectorAll('.quickcopy-menu.is-open').forEach((openMenu) => { if (openMenu !== menu) openMenu.classList.remove('is-open'); }); menu.classList.toggle('is-open'); };
  wrapper.append(trigger, menu); actions.appendChild(wrapper);
}
function scan() { document.querySelectorAll('article[data-testid="tweet"], article[role="article"]').forEach((post) => { if (!post.hasAttribute(INJECTED)) addQuickCopy(post).catch((error) => { post.removeAttribute(INJECTED); reportQuickCopyError('post injection failed', error); }); }); }
function safeScan() { try { scan(); } catch (error) { reportQuickCopyError('post scan failed', error); } }
const observer = new MutationObserver(safeScan); observer.observe(document.documentElement, { childList: true, subtree: true });
chrome.storage.onChanged.addListener((changes, area) => { if (area !== 'local' || (!changes[SETTINGS_KEY] && !changes[QUICKCOPY_KEY])) return; document.querySelectorAll(`[${INJECTED}]`).forEach(clearInjected); safeScan(); });
safeScan();
