const KEY = 'quickcopy_wallets';
const SETTINGS_KEY = 'quickcopy_settings';
const WALLET_LIMIT = 10;
const defaults = [{ id: 'demo', name: 'Main Ethereum', network: 'Ethereum', address: '0x7A3f19d5B7D6a44f6aE3cB' }];
const defaultSettings = { color: 'lime', label: true, shape: 'rounded', size: 'medium', theme: 'dark' };
const walletsEl = document.querySelector('#wallets');
const form = document.querySelector('#form');
const add = document.querySelector('#add');
const nameInput = document.querySelector('#name');
const networkInput = document.querySelector('#network');
const addressInput = document.querySelector('#address');
const saveWallet = document.querySelector('#saveWallet');
const themeToggle = document.querySelector('#themeToggle');
const labelInput = document.querySelector('#label');
const labelSwitch = document.querySelector('#labelSwitch');
const livePreview = document.querySelector('#livePreview');
const livePreviewTrigger = document.querySelector('#livePreviewTrigger');
const livePreviewReadout = document.querySelector('#livePreviewReadout');
const livePreviewLabel = document.querySelector('#livePreviewLabel');
let wallets = [];
let settings = { ...defaultSettings };
let editingId = null;
let draggedWalletId = null;

const short = (value) => value.length > 14 ? `${value.slice(0, 6)}...${value.slice(-4)}` : value;
const element = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
const svgElement = (tag, attributes) => { const node = document.createElementNS('http://www.w3.org/2000/svg', tag); Object.entries(attributes).forEach(([name, value]) => node.setAttribute(name, value)); return node; };
const networkMark = (network) => { const svg = svgElement('svg', { viewBox: '0 0 24 24', 'aria-label': network }); svg.appendChild(svgElement('path', { d: network === 'Solana' ? 'M5 6h11l3 3H8L5 6Zm3 4h11l-3 3H5l3-3Zm-3 5h11l3 3H8l-3-3Z' : 'm12 2 6 10-6 3.5L6 12l6-10Zm0 15.5 6-3.3-6 7.8-6-7.8 6 3.3Z', fill: 'currentColor' })); return svg; };
const save = () => chrome.storage.local.set({ [KEY]: wallets.slice(0, WALLET_LIMIT) });
const saveSettings = () => chrome.storage.local.set({ [SETTINGS_KEY]: settings });
const closeForm = () => { editingId = null; form.reset(); form.classList.remove('open'); saveWallet.textContent = 'Save wallet'; };
const openForm = (wallet = null) => { editingId = wallet?.id ?? null; nameInput.value = wallet?.name ?? ''; networkInput.value = wallet?.network ?? 'Ethereum'; addressInput.value = wallet?.address ?? ''; saveWallet.textContent = wallet ? 'Save changes' : 'Save wallet'; form.classList.add('open'); nameInput.focus(); };
const applyTheme = () => { document.body.dataset.theme = settings.theme; themeToggle.textContent = settings.theme === 'dark' ? '☼' : '◐'; themeToggle.setAttribute('aria-label', settings.theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'); };
const applyControlState = () => { labelInput.checked = settings.label; labelSwitch.classList.toggle('on', settings.label); labelSwitch.setAttribute('aria-pressed', String(settings.label)); document.querySelectorAll('.color').forEach((button) => button.classList.toggle('active', button.dataset.color === settings.color)); document.querySelectorAll('.shape').forEach((button) => button.classList.toggle('active', button.dataset.shape === settings.shape)); document.querySelectorAll('.size').forEach((button) => button.classList.toggle('active', button.dataset.size === settings.size)); livePreview.className = `popup-live-preview preview-${settings.color}`; livePreviewTrigger.className = `popup-trigger-preview preview-${settings.shape} preview-${settings.size}${settings.label ? '' : ' label-off'}`; livePreviewReadout.textContent = `${settings.shape.toUpperCase()} · ${settings.size.toUpperCase()}`; livePreviewLabel.hidden = !settings.label; };
const render = () => { walletsEl.replaceChildren(); wallets.slice(0, WALLET_LIMIT).forEach((wallet, index) => { const row = element('div', `row ${index === 0 ? 'active' : ''}`); const drag = element('button', 'drag', '↕'); drag.draggable = true; drag.setAttribute('aria-label', 'Reorder wallet'); drag.title = 'Drag to reorder'; const symbol = element('div', 'symbol'); symbol.appendChild(networkMark(wallet.network)); const info = element('div', 'info'); info.append(element('span', 'name', wallet.name), element('span', 'meta', `${wallet.network} · ${short(wallet.address)}`)); const copy = element('button', 'copy', 'COPY'); const edit = element('button', 'edit', '✎'); edit.setAttribute('aria-label', 'Edit wallet'); edit.title = 'Edit wallet'; const remove = element('button', 'delete', '×'); remove.setAttribute('aria-label', 'Delete wallet'); row.append(drag, symbol, info, copy, edit, remove); drag.ondragstart = (event) => { draggedWalletId = wallet.id; event.dataTransfer.effectAllowed = 'move'; }; drag.ondragend = () => { draggedWalletId = null; row.classList.remove('drag-over'); }; row.ondragover = (event) => { event.preventDefault(); if (draggedWalletId !== wallet.id) row.classList.add('drag-over'); }; row.ondragleave = () => row.classList.remove('drag-over'); row.ondrop = (event) => { event.preventDefault(); row.classList.remove('drag-over'); if (!draggedWalletId || draggedWalletId === wallet.id) return; const sourceIndex = wallets.findIndex((item) => item.id === draggedWalletId); const targetIndex = wallets.findIndex((item) => item.id === wallet.id); if (sourceIndex < 0 || targetIndex < 0) return; const [moved] = wallets.splice(sourceIndex, 1); wallets.splice(targetIndex, 0, moved); draggedWalletId = null; save(); render(); }; copy.onclick = async () => { await navigator.clipboard.writeText(wallet.address); copy.textContent = 'COPIED'; copy.classList.add('copied'); setTimeout(() => { copy.textContent = 'COPY'; copy.classList.remove('copied'); }, 1200); }; edit.onclick = () => openForm(wallet); remove.onclick = () => { wallets = wallets.filter((item) => item.id !== wallet.id); save(); render(); }; walletsEl.appendChild(row); }); add.disabled = wallets.length >= WALLET_LIMIT; add.textContent = wallets.length >= WALLET_LIMIT ? 'Wallet limit reached' : '+ Add wallet'; };
chrome.storage.local.get({ [KEY]: defaults, [SETTINGS_KEY]: defaultSettings }, (result) => { wallets = Array.isArray(result[KEY]) ? result[KEY].slice(0, WALLET_LIMIT) : defaults; settings = { ...defaultSettings, ...result[SETTINGS_KEY] }; settings.shape = settings.shape === 'circle' ? 'circle' : 'rounded'; settings.size = settings.size === 'large' ? 'large' : 'medium'; settings.theme = settings.theme === 'light' ? 'light' : 'dark'; applyTheme(); applyControlState(); render(); });
add.onclick = () => { if (wallets.length < WALLET_LIMIT) openForm(); };
themeToggle.onclick = () => { settings.theme = settings.theme === 'dark' ? 'light' : 'dark'; applyTheme(); saveSettings(); };
document.querySelectorAll('.shape').forEach((button) => { button.onclick = () => { settings.shape = button.dataset.shape === 'circle' ? 'circle' : 'rounded'; saveSettings(); applyControlState(); }; });
document.querySelectorAll('.size').forEach((button) => { button.onclick = () => { settings.size = button.dataset.size === 'large' ? 'large' : 'medium'; saveSettings(); applyControlState(); }; });
document.querySelectorAll('.color').forEach((button) => { button.onclick = () => { settings.color = button.dataset.color; saveSettings(); applyControlState(); }; });
labelSwitch.onclick = () => { settings.label = !settings.label; saveSettings(); applyControlState(); };
form.onsubmit = (event) => { event.preventDefault(); const name = nameInput.value.trim(); const network = networkInput.value; const address = addressInput.value.trim(); if (!name || !address) return; if (editingId) { wallets = wallets.map((wallet) => wallet.id === editingId ? { ...wallet, name, network, address } : wallet); } else { if (wallets.length >= WALLET_LIMIT) return; wallets.push({ id: crypto.randomUUID(), name, network, address }); } save(); render(); closeForm(); };
